M48
; DRILL file {KiCad (6.0.10)} date Thu May  4 16:05:09 2023
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2023-05-04T16:05:09+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X62044Y-57863
X62044Y-59463
X62044Y-61063
X62044Y-62663
X62044Y-64263
T0
M30
